export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAIL = "FETCH_COUNTRIES_FAIL";
export const FILTER_REGION = "FILTER REGION";
export const FILTER_SEARCH = "FILTER_SEARCH";