export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAIL = "FETCH_COUNTRIES_FAIL";
export const CHANGE_SEARCH = "CHANGE_SEARCH";
export const CHANGE_REGION = "CHANGE_REGION";